### ISSUE TITLE
Python shebangs assume python2 is default Python

### ISSUE THREAD

**Issue by daveuu** [LivGen/LMAT#1]
LMAT pipelines fail on GNU/Linux distributions which have moved their default Python version to 3 (e.g. ArchLinux). Shebang lines which do not specify a Python version but are written in Python 2.x will fail in some instances e.g.

```
print 'hello'
```

If python2 is specified e.g. `#!/usr/bin/python2` the code works regardless of the default Python version in the system. In the mean time this is a fix:

```
sed -i 's"#!/usr/bin/python"#!/usr/bin/python2"g' LMAT-1.2.6/bin/*.py
sed -i 's"#!/usr/bin/env python"#!/usr/bin/env python2"g' LMAT-1.2.6/bin/*.py
```

**Comment by khyox** [comment]
I completely missed this, sorry! The python scripts were ported to python3 adding Python2 compatibility long time ago. This should be no more an issue. Feel free of reopen the issue otherwise.
