### ISSUE TITLE
perl scripts: #!/usr/bin/perl -w   => #!/usr/bin/env perl

### ISSUE THREAD

**Issue by tseemann** [LivGen/LMAT#5]
The above forces system perl and the old warnings syntax. 
For conda/brew we need to use the first Perl in the $PATH instead.
This is the standard way to achieve this:
```
#!/usr/bin/env perl
use warnings;
```

Same for `#!/usr/bin/env python` (or `python3`.

**Comment by jeallen** [comment]
I push this suggested change to the *.pl *.py files.
